# Generated by Django 4.2.11 on 2026-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetailsack',
            name='correction_comments',
            field=models.TextField(blank=True, help_text='Specify any incorrect or mistaken fields in the bank details.', null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='is_dark_mode',
            field=models.BooleanField(default=False, help_text='Enable dark mode for a low-light-friendly interface.'),
        ),
    ]
