# Generated by Django 4.2.30 on 2026-05-15 03:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('configs', '0001_initial'),
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='tds_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='configs.tds'),
        ),
    ]
