# Generated by Django 4.2.11 on 2026-05-15 09:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0002_alter_bankdetailsack_correction_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payee',
            name='hrm_id',
            field=models.CharField(help_text='Payee ID obtained from Zoho people', max_length=10, unique=True),
        ),
    ]
