# Generated by Django 4.2.11 on 2026-05-18 10:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0003_alter_payee_hrm_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankdetailsack',
            name='bank_details',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='acknowledgements', to='payees.bankdetails'),
        ),
    ]
