# Generated by Django 4.2.11 on 2026-05-22 08:50

from django.db import migrations, models
from django.db.models import Count


def remove_duplicate_bank_detail_acknowledgements(apps, schema_editor):
    BankDetailsAck = apps.get_model('payees', 'BankDetailsAck')
    duplicate_bank_details = (
        BankDetailsAck.objects
        .exclude(bank_details__isnull=True)
        .values('bank_details_id')
        .annotate(ack_count=Count('id'))
        .filter(ack_count__gt=1)
        .values_list('bank_details_id', flat=True)
    )
    for bank_details_id in duplicate_bank_details:
        ack_ids = list(
            BankDetailsAck.objects
            .filter(bank_details_id=bank_details_id)
            .order_by('uploaded_date', 'id')
            .values_list('id', flat=True)
        )
        if len(ack_ids) > 1:
            BankDetailsAck.objects.filter(id__in=ack_ids[1:]).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0004_bankdetailsack_bank_details'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_bank_detail_acknowledgements, migrations.RunPython.noop),
        migrations.AddConstraint(
            model_name='bankdetailsack',
            constraint=models.UniqueConstraint(condition=models.Q(bank_details__isnull=False), fields=('bank_details',), name='unique_ack_per_bank_details'),
        ),
    ]
