# Generated by Codex on 2026-05-22

from collections import defaultdict

from django.db import migrations, models
import django.db.models.deletion


def backfill_or_remove_legacy_null_acknowledgements(apps, schema_editor):
    BankDetails = apps.get_model('payees', 'BankDetails')
    BankDetailsAck = apps.get_model('payees', 'BankDetailsAck')

    payee_ids = list(
        BankDetailsAck.objects
        .filter(bank_details__isnull=True)
        .values_list('payee_id', flat=True)
        .distinct()
    )
    if not payee_ids:
        return

    bank_details_ids_by_payee = defaultdict(list)
    for bank_details_id, payee_id in (
        BankDetails.objects
        .filter(payee_id__in=payee_ids)
        .order_by('payee_id', 'id')
        .values_list('id', 'payee_id')
    ):
        bank_details_ids_by_payee[payee_id].append(bank_details_id)

    null_ack_ids_by_payee = defaultdict(list)
    for ack_id, payee_id in (
        BankDetailsAck.objects
        .filter(payee_id__in=payee_ids, bank_details__isnull=True)
        .order_by('payee_id', 'uploaded_date', 'id')
        .values_list('id', 'payee_id')
    ):
        null_ack_ids_by_payee[payee_id].append(ack_id)

    acknowledged_bank_details_ids = set(
        BankDetailsAck.objects
        .filter(bank_details__payee_id__in=payee_ids)
        .exclude(bank_details__isnull=True)
        .values_list('bank_details_id', flat=True)
    )

    ack_updates = {}
    ack_ids_to_delete = []

    for payee_id, null_ack_ids in null_ack_ids_by_payee.items():
        bank_details_ids = bank_details_ids_by_payee.get(payee_id, [])
        if not bank_details_ids:
            ack_ids_to_delete.extend(null_ack_ids)
            continue

        unacknowledged_bank_details_ids = [
            bank_details_id
            for bank_details_id in bank_details_ids
            if bank_details_id not in acknowledged_bank_details_ids
        ]

        if not unacknowledged_bank_details_ids:
            ack_ids_to_delete.extend(null_ack_ids)
            continue

        ack_updates[null_ack_ids[0]] = unacknowledged_bank_details_ids[0]
        if len(null_ack_ids) > 1:
            ack_ids_to_delete.extend(null_ack_ids[1:])

    if ack_updates:
        acks = list(BankDetailsAck.objects.filter(id__in=ack_updates.keys()))
        for ack in acks:
            ack.bank_details_id = ack_updates[ack.id]
        BankDetailsAck.objects.bulk_update(acks, ['bank_details'])

    if ack_ids_to_delete:
        BankDetailsAck.objects.filter(id__in=ack_ids_to_delete).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0005_bankdetailsack_unique_ack_per_bank_details'),
    ]

    operations = [
        migrations.RunPython(
            backfill_or_remove_legacy_null_acknowledgements,
            migrations.RunPython.noop,
        ),
        migrations.RemoveConstraint(
            model_name='bankdetailsack',
            name='unique_ack_per_bank_details',
        ),
        migrations.AlterField(
            model_name='bankdetailsack',
            name='bank_details',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='acknowledgements',
                to='payees.bankdetails',
            ),
        ),
        migrations.AddConstraint(
            model_name='bankdetailsack',
            constraint=models.UniqueConstraint(
                fields=('bank_details',),
                name='unique_ack_per_bank_details',
            ),
        ),
    ]
