# Generated by Django 4.2.30 on 2026-07-16 06:26
# NOTE: This migration alters existing plaintext columns to EncryptedCharField/EncryptedTextField.
# Rows written before this migration are stored as plaintext; after migration the ORM will
# attempt to decrypt those values and may raise errors. Before deploying, run a backfill
# script that reads each row via raw SQL (bypassing the ORM), encrypts the value, and
# writes it back — or truncate/re-seed non-production data. For production, perform a
# staged migration: add new encrypted columns, backfill from plaintext, then drop old columns.

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0007_bankdetails_unique_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_no',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='branch_address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='micr_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='swift_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='pan_no',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=10, null=True),
        ),
    ]
