# Generated by Django 4.2.30 on 2026-07-16 06:26

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0007_bankdetails_unique_payee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankdetails',
            name='account_no',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='branch_address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='ifsc_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='micr_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='bankdetails',
            name='swift_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payee',
            name='pan_no',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=10, null=True, unique=True),
        ),
    ]
