# Generated by Django 4.2.30 on 2026-05-14 12:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Component',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('component_name', models.CharField(max_length=100)),
                ('operation', models.CharField(choices=[('sum', 'Sum'), ('subtract', 'Subtract')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='TDS',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tds_legal_name', models.CharField(choices=[('technical-consultants', 'Technical Consultants'), ('professional-consultant', 'Professional Consultant'), ('employment', 'Employment'), ('apprentices', 'Apprentices')], max_length=50, unique=True)),
                ('tds_percentage', models.FloatField()),
            ],
            options={
                'verbose_name': 'Tax Deducted at Source',
                'verbose_name_plural': 'Tax Deducted at Source',
            },
        ),
    ]
