# Generated by Django 4.2.30 on 2026-05-14 12:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import payroll.upload_helpers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('configs', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('payees', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form16',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=10, null=True)),
                ('uploaded_on', models.DateTimeField(auto_now_add=True)),
                ('form16_zip_file', models.FileField(upload_to='uploads/payroll/form16/', validators=[payroll.upload_helpers.validate_zip_file])),
                ('is_extracted', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PayRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.IntegerField()),
                ('year', models.IntegerField()),
                ('status', models.CharField(choices=[('due', 'DUE'), ('in_progress', 'IN PROGRESS'), ('completed', 'COMPLETED'), ('rejected', 'REJECTED'), ('approved', 'APPROVED')], default='due', max_length=20)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('error_log', models.TextField(blank=True, help_text='shows only if any error occur in payees data ', null=True)),
                ('created_by', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Pay Run',
                'verbose_name_plural': 'Pay Runs',
            },
        ),
        migrations.CreateModel(
            name='PayRecordRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_created', models.DateTimeField(auto_now_add=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('bank_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_number', models.CharField(blank=True, max_length=16, null=True)),
                ('account_holder_name', models.CharField(blank=True, max_length=100, null=True)),
                ('account_type', models.CharField(blank=True, max_length=10, null=True)),
                ('ifsc_code', models.CharField(blank=True, max_length=100, null=True)),
                ('micr_code', models.CharField(blank=True, max_length=100, null=True)),
                ('swift_code', models.CharField(blank=True, max_length=100, null=True)),
                ('branch_address', models.TextField(blank=True, null=True)),
                ('tds_percentage', models.FloatField(blank=True, null=True)),
                ('gross_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('net_income', models.FloatField(blank=True, null=True)),
                ('pay_run', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='payroll.payrun')),
                ('payee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payees.payee')),
            ],
            options={
                'verbose_name': 'Pay Record Register',
                'verbose_name_plural': 'Pay Record Registers',
                'ordering': ['-record_created'],
                'unique_together': {('payee', 'pay_run')},
            },
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('label', models.CharField(max_length=50)),
                ('payee', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='payees.payee')),
            ],
            options={
                'verbose_name': 'Payment',
                'verbose_name_plural': 'Payments',
            },
        ),
        migrations.CreateModel(
            name='Form16Entries',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_16', models.FileField(upload_to=payroll.upload_helpers.form16_extracted_path)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.form16')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payees.payee')),
            ],
        ),
        migrations.CreateModel(
            name='ComponentValue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10)),
                ('component', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='configs.component')),
                ('pay_record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='payroll.payrecordregister')),
            ],
        ),
    ]
