# Generated by Django 4.2.11 on 2026-05-15 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrun',
            name='error_log',
            field=models.TextField(blank=True, help_text='Shows only if any errors occur in payees data.', null=True),
        ),
    ]
