# Generated by Django 4.2.11 on 2026-05-18 10:33

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0002_alter_payrun_error_log'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrun',
            name='month',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(12)]),
        ),
    ]
