# Generated by Django 4.2.11 on 2026-05-18 11:03

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import payroll.upload_helpers


class Migration(migrations.Migration):

    dependencies = [
        ('payees', '0004_bankdetailsack_bank_details'),
        ('payroll', '0003_alter_payrun_month'),
    ]

    operations = [
        migrations.CreateModel(
            name='Form16Entry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('form_16', models.FileField(upload_to=payroll.upload_helpers.form16_extracted_path)),
                ('financial_year', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entries', to='payroll.form16')),
                ('payee', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='payees.payee')),
            ],
            options={
                'verbose_name': 'Form 16 Entry',
                'verbose_name_plural': 'Form 16 Entries',
            },
        ),
        migrations.AlterField(
            model_name='payrun',
            name='year',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(2000), django.core.validators.MaxValueValidator(2100)]),
        ),
        migrations.AlterUniqueTogether(
            name='payrun',
            unique_together={('month', 'year')},
        ),
        migrations.DeleteModel(
            name='Form16Entries',
        ),
    ]
