# Generated by Django 4.2.30 on 2026-07-16 06:26
# NOTE: This migration alters existing plaintext bank columns to EncryptedCharField/EncryptedTextField.
# Rows written before this migration are stored as plaintext; the ORM will attempt to decrypt
# those values after migration and may raise errors. Before deploying to production, run a
# backfill that reads each row via raw SQL, encrypts the value using the same key, and writes
# it back — or perform a staged migration (add encrypted columns, backfill, drop originals).

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_form16_extraction_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecordregister',
            name='account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='branch_address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='ifsc_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='micr_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='swift_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
