# Generated by Django 4.2.30 on 2026-07-16 06:26

from django.db import migrations
import encrypted_model_fields.fields


class Migration(migrations.Migration):

    dependencies = [
        ('payroll', '0007_form16_extraction_summary'),
    ]

    operations = [
        migrations.AlterField(
            model_name='payrecordregister',
            name='account_number',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='branch_address',
            field=encrypted_model_fields.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='ifsc_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='micr_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='payrecordregister',
            name='swift_code',
            field=encrypted_model_fields.fields.EncryptedCharField(blank=True, max_length=100, null=True),
        ),
    ]
